package Sea.incubator.sgdeb.model;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

@Data
@Entity
@Table(name = "Participe")
public class Note {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;


    @ManyToOne
    private GrilleExamen idGrilleExamen;

    private double notes;
    private String nom;
    private String matricule;
    private String anonimat = "";
    private String typeEval;
    private String niveau;
    private String UE;
    private String filiere;
    private String anneAcademique;
    private String session;
    private int semestre;
    private int ExamenNoteSur;
    private double credit;

    @CreationTimestamp
    @Column(updatable = false, nullable = false)
    private LocalDateTime dateEnregistrement;

    @UpdateTimestamp
    private LocalDateTime updateAt; // Correct spelling for consistency

    private LocalDateTime delectAt; // Consider renaming to deleteAt for clarity

    @ManyToOne
    @JoinColumn(name = "importation_id")
    private Importation importation;

    // Getter and Setter methods (auto-generated by Lombok)
}
